package appo.task.mapper;

import appo.task.domain.CwGlIncomeCost;
import appo.task.domain.CwGlIncomeCostExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CwGlIncomeCostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    long countByExample(CwGlIncomeCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    int deleteByExample(CwGlIncomeCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    int insert(CwGlIncomeCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    int insertSelective(CwGlIncomeCost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    List<CwGlIncomeCost> selectByExample(CwGlIncomeCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    int updateByExampleSelective(@Param("record") CwGlIncomeCost record, @Param("example") CwGlIncomeCostExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    int updateByExample(@Param("record") CwGlIncomeCost record, @Param("example") CwGlIncomeCostExample example);
}