package appo.task.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CwGlIncomeCostExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public CwGlIncomeCostExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateIsNull() {
            addCriterion("LAST_UPDATED_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateIsNotNull() {
            addCriterion("LAST_UPDATED_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATE =", value, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATE <>", value, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATED_DATE >", value, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATE >=", value, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateLessThan(Date value) {
            addCriterion("LAST_UPDATED_DATE <", value, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATED_DATE <=", value, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateIn(List<Date> values) {
            addCriterion("LAST_UPDATED_DATE in", values, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATED_DATE not in", values, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_DATE between", value1, value2, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdatedDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATED_DATE not between", value1, value2, "lastUpdatedDate");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNull() {
            addCriterion("COMPANYCODE is null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIsNotNull() {
            addCriterion("COMPANYCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCompanycodeEqualTo(String value) {
            addCriterion("COMPANYCODE =", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotEqualTo(String value) {
            addCriterion("COMPANYCODE <>", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThan(String value) {
            addCriterion("COMPANYCODE >", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeGreaterThanOrEqualTo(String value) {
            addCriterion("COMPANYCODE >=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThan(String value) {
            addCriterion("COMPANYCODE <", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLessThanOrEqualTo(String value) {
            addCriterion("COMPANYCODE <=", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeLike(String value) {
            addCriterion("COMPANYCODE like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotLike(String value) {
            addCriterion("COMPANYCODE not like", value, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeIn(List<String> values) {
            addCriterion("COMPANYCODE in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotIn(List<String> values) {
            addCriterion("COMPANYCODE not in", values, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeBetween(String value1, String value2) {
            addCriterion("COMPANYCODE between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andCompanycodeNotBetween(String value1, String value2) {
            addCriterion("COMPANYCODE not between", value1, value2, "companycode");
            return (Criteria) this;
        }

        public Criteria andBillSourceIsNull() {
            addCriterion("BILL_SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andBillSourceIsNotNull() {
            addCriterion("BILL_SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andBillSourceEqualTo(String value) {
            addCriterion("BILL_SOURCE =", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceNotEqualTo(String value) {
            addCriterion("BILL_SOURCE <>", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceGreaterThan(String value) {
            addCriterion("BILL_SOURCE >", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceGreaterThanOrEqualTo(String value) {
            addCriterion("BILL_SOURCE >=", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceLessThan(String value) {
            addCriterion("BILL_SOURCE <", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceLessThanOrEqualTo(String value) {
            addCriterion("BILL_SOURCE <=", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceLike(String value) {
            addCriterion("BILL_SOURCE like", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceNotLike(String value) {
            addCriterion("BILL_SOURCE not like", value, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceIn(List<String> values) {
            addCriterion("BILL_SOURCE in", values, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceNotIn(List<String> values) {
            addCriterion("BILL_SOURCE not in", values, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceBetween(String value1, String value2) {
            addCriterion("BILL_SOURCE between", value1, value2, "billSource");
            return (Criteria) this;
        }

        public Criteria andBillSourceNotBetween(String value1, String value2) {
            addCriterion("BILL_SOURCE not between", value1, value2, "billSource");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeIsNull() {
            addCriterion("CBDLCODE is null");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeIsNotNull() {
            addCriterion("CBDLCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeEqualTo(String value) {
            addCriterion("CBDLCODE =", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeNotEqualTo(String value) {
            addCriterion("CBDLCODE <>", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeGreaterThan(String value) {
            addCriterion("CBDLCODE >", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CBDLCODE >=", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeLessThan(String value) {
            addCriterion("CBDLCODE <", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeLessThanOrEqualTo(String value) {
            addCriterion("CBDLCODE <=", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeLike(String value) {
            addCriterion("CBDLCODE like", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeNotLike(String value) {
            addCriterion("CBDLCODE not like", value, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeIn(List<String> values) {
            addCriterion("CBDLCODE in", values, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeNotIn(List<String> values) {
            addCriterion("CBDLCODE not in", values, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeBetween(String value1, String value2) {
            addCriterion("CBDLCODE between", value1, value2, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andCbdlcodeNotBetween(String value1, String value2) {
            addCriterion("CBDLCODE not between", value1, value2, "cbdlcode");
            return (Criteria) this;
        }

        public Criteria andShipDateIsNull() {
            addCriterion("SHIP_DATE is null");
            return (Criteria) this;
        }

        public Criteria andShipDateIsNotNull() {
            addCriterion("SHIP_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andShipDateEqualTo(Date value) {
            addCriterion("SHIP_DATE =", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotEqualTo(Date value) {
            addCriterion("SHIP_DATE <>", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateGreaterThan(Date value) {
            addCriterion("SHIP_DATE >", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateGreaterThanOrEqualTo(Date value) {
            addCriterion("SHIP_DATE >=", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateLessThan(Date value) {
            addCriterion("SHIP_DATE <", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateLessThanOrEqualTo(Date value) {
            addCriterion("SHIP_DATE <=", value, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateIn(List<Date> values) {
            addCriterion("SHIP_DATE in", values, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotIn(List<Date> values) {
            addCriterion("SHIP_DATE not in", values, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateBetween(Date value1, Date value2) {
            addCriterion("SHIP_DATE between", value1, value2, "shipDate");
            return (Criteria) this;
        }

        public Criteria andShipDateNotBetween(Date value1, Date value2) {
            addCriterion("SHIP_DATE not between", value1, value2, "shipDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateIsNull() {
            addCriterion("INCOME_DATE is null");
            return (Criteria) this;
        }

        public Criteria andIncomeDateIsNotNull() {
            addCriterion("INCOME_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andIncomeDateEqualTo(Date value) {
            addCriterion("INCOME_DATE =", value, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateNotEqualTo(Date value) {
            addCriterion("INCOME_DATE <>", value, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateGreaterThan(Date value) {
            addCriterion("INCOME_DATE >", value, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateGreaterThanOrEqualTo(Date value) {
            addCriterion("INCOME_DATE >=", value, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateLessThan(Date value) {
            addCriterion("INCOME_DATE <", value, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateLessThanOrEqualTo(Date value) {
            addCriterion("INCOME_DATE <=", value, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateIn(List<Date> values) {
            addCriterion("INCOME_DATE in", values, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateNotIn(List<Date> values) {
            addCriterion("INCOME_DATE not in", values, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateBetween(Date value1, Date value2) {
            addCriterion("INCOME_DATE between", value1, value2, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andIncomeDateNotBetween(Date value1, Date value2) {
            addCriterion("INCOME_DATE not between", value1, value2, "incomeDate");
            return (Criteria) this;
        }

        public Criteria andCcuscodeIsNull() {
            addCriterion("CCUSCODE is null");
            return (Criteria) this;
        }

        public Criteria andCcuscodeIsNotNull() {
            addCriterion("CCUSCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCcuscodeEqualTo(String value) {
            addCriterion("CCUSCODE =", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeNotEqualTo(String value) {
            addCriterion("CCUSCODE <>", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeGreaterThan(String value) {
            addCriterion("CCUSCODE >", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeGreaterThanOrEqualTo(String value) {
            addCriterion("CCUSCODE >=", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeLessThan(String value) {
            addCriterion("CCUSCODE <", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeLessThanOrEqualTo(String value) {
            addCriterion("CCUSCODE <=", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeLike(String value) {
            addCriterion("CCUSCODE like", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeNotLike(String value) {
            addCriterion("CCUSCODE not like", value, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeIn(List<String> values) {
            addCriterion("CCUSCODE in", values, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeNotIn(List<String> values) {
            addCriterion("CCUSCODE not in", values, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeBetween(String value1, String value2) {
            addCriterion("CCUSCODE between", value1, value2, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCcuscodeNotBetween(String value1, String value2) {
            addCriterion("CCUSCODE not between", value1, value2, "ccuscode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeIsNull() {
            addCriterion("CINVCODE is null");
            return (Criteria) this;
        }

        public Criteria andCinvcodeIsNotNull() {
            addCriterion("CINVCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCinvcodeEqualTo(String value) {
            addCriterion("CINVCODE =", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeNotEqualTo(String value) {
            addCriterion("CINVCODE <>", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeGreaterThan(String value) {
            addCriterion("CINVCODE >", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CINVCODE >=", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeLessThan(String value) {
            addCriterion("CINVCODE <", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeLessThanOrEqualTo(String value) {
            addCriterion("CINVCODE <=", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeLike(String value) {
            addCriterion("CINVCODE like", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeNotLike(String value) {
            addCriterion("CINVCODE not like", value, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeIn(List<String> values) {
            addCriterion("CINVCODE in", values, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeNotIn(List<String> values) {
            addCriterion("CINVCODE not in", values, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeBetween(String value1, String value2) {
            addCriterion("CINVCODE between", value1, value2, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andCinvcodeNotBetween(String value1, String value2) {
            addCriterion("CINVCODE not between", value1, value2, "cinvcode");
            return (Criteria) this;
        }

        public Criteria andIquantityIsNull() {
            addCriterion("IQUANTITY is null");
            return (Criteria) this;
        }

        public Criteria andIquantityIsNotNull() {
            addCriterion("IQUANTITY is not null");
            return (Criteria) this;
        }

        public Criteria andIquantityEqualTo(Short value) {
            addCriterion("IQUANTITY =", value, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityNotEqualTo(Short value) {
            addCriterion("IQUANTITY <>", value, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityGreaterThan(Short value) {
            addCriterion("IQUANTITY >", value, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityGreaterThanOrEqualTo(Short value) {
            addCriterion("IQUANTITY >=", value, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityLessThan(Short value) {
            addCriterion("IQUANTITY <", value, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityLessThanOrEqualTo(Short value) {
            addCriterion("IQUANTITY <=", value, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityIn(List<Short> values) {
            addCriterion("IQUANTITY in", values, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityNotIn(List<Short> values) {
            addCriterion("IQUANTITY not in", values, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityBetween(Short value1, Short value2) {
            addCriterion("IQUANTITY between", value1, value2, "iquantity");
            return (Criteria) this;
        }

        public Criteria andIquantityNotBetween(Short value1, Short value2) {
            addCriterion("IQUANTITY not between", value1, value2, "iquantity");
            return (Criteria) this;
        }

        public Criteria andExchangeNameIsNull() {
            addCriterion("EXCHANGE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andExchangeNameIsNotNull() {
            addCriterion("EXCHANGE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeNameEqualTo(String value) {
            addCriterion("EXCHANGE_NAME =", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameNotEqualTo(String value) {
            addCriterion("EXCHANGE_NAME <>", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameGreaterThan(String value) {
            addCriterion("EXCHANGE_NAME >", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameGreaterThanOrEqualTo(String value) {
            addCriterion("EXCHANGE_NAME >=", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameLessThan(String value) {
            addCriterion("EXCHANGE_NAME <", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameLessThanOrEqualTo(String value) {
            addCriterion("EXCHANGE_NAME <=", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameLike(String value) {
            addCriterion("EXCHANGE_NAME like", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameNotLike(String value) {
            addCriterion("EXCHANGE_NAME not like", value, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameIn(List<String> values) {
            addCriterion("EXCHANGE_NAME in", values, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameNotIn(List<String> values) {
            addCriterion("EXCHANGE_NAME not in", values, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameBetween(String value1, String value2) {
            addCriterion("EXCHANGE_NAME between", value1, value2, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeNameNotBetween(String value1, String value2) {
            addCriterion("EXCHANGE_NAME not between", value1, value2, "exchangeName");
            return (Criteria) this;
        }

        public Criteria andExchangeRateIsNull() {
            addCriterion("EXCHANGE_RATE is null");
            return (Criteria) this;
        }

        public Criteria andExchangeRateIsNotNull() {
            addCriterion("EXCHANGE_RATE is not null");
            return (Criteria) this;
        }

        public Criteria andExchangeRateEqualTo(Short value) {
            addCriterion("EXCHANGE_RATE =", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateNotEqualTo(Short value) {
            addCriterion("EXCHANGE_RATE <>", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateGreaterThan(Short value) {
            addCriterion("EXCHANGE_RATE >", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateGreaterThanOrEqualTo(Short value) {
            addCriterion("EXCHANGE_RATE >=", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateLessThan(Short value) {
            addCriterion("EXCHANGE_RATE <", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateLessThanOrEqualTo(Short value) {
            addCriterion("EXCHANGE_RATE <=", value, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateIn(List<Short> values) {
            addCriterion("EXCHANGE_RATE in", values, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateNotIn(List<Short> values) {
            addCriterion("EXCHANGE_RATE not in", values, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateBetween(Short value1, Short value2) {
            addCriterion("EXCHANGE_RATE between", value1, value2, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andExchangeRateNotBetween(Short value1, Short value2) {
            addCriterion("EXCHANGE_RATE not between", value1, value2, "exchangeRate");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceIsNull() {
            addCriterion("ITAXUNITPRICE is null");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceIsNotNull() {
            addCriterion("ITAXUNITPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceEqualTo(Short value) {
            addCriterion("ITAXUNITPRICE =", value, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceNotEqualTo(Short value) {
            addCriterion("ITAXUNITPRICE <>", value, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceGreaterThan(Short value) {
            addCriterion("ITAXUNITPRICE >", value, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceGreaterThanOrEqualTo(Short value) {
            addCriterion("ITAXUNITPRICE >=", value, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceLessThan(Short value) {
            addCriterion("ITAXUNITPRICE <", value, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceLessThanOrEqualTo(Short value) {
            addCriterion("ITAXUNITPRICE <=", value, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceIn(List<Short> values) {
            addCriterion("ITAXUNITPRICE in", values, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceNotIn(List<Short> values) {
            addCriterion("ITAXUNITPRICE not in", values, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceBetween(Short value1, Short value2) {
            addCriterion("ITAXUNITPRICE between", value1, value2, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andItaxunitpriceNotBetween(Short value1, Short value2) {
            addCriterion("ITAXUNITPRICE not between", value1, value2, "itaxunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceIsNull() {
            addCriterion("IUNITPRICE is null");
            return (Criteria) this;
        }

        public Criteria andIunitpriceIsNotNull() {
            addCriterion("IUNITPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andIunitpriceEqualTo(Short value) {
            addCriterion("IUNITPRICE =", value, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceNotEqualTo(Short value) {
            addCriterion("IUNITPRICE <>", value, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceGreaterThan(Short value) {
            addCriterion("IUNITPRICE >", value, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceGreaterThanOrEqualTo(Short value) {
            addCriterion("IUNITPRICE >=", value, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceLessThan(Short value) {
            addCriterion("IUNITPRICE <", value, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceLessThanOrEqualTo(Short value) {
            addCriterion("IUNITPRICE <=", value, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceIn(List<Short> values) {
            addCriterion("IUNITPRICE in", values, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceNotIn(List<Short> values) {
            addCriterion("IUNITPRICE not in", values, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceBetween(Short value1, Short value2) {
            addCriterion("IUNITPRICE between", value1, value2, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andIunitpriceNotBetween(Short value1, Short value2) {
            addCriterion("IUNITPRICE not between", value1, value2, "iunitprice");
            return (Criteria) this;
        }

        public Criteria andInatmoneyIsNull() {
            addCriterion("INATMONEY is null");
            return (Criteria) this;
        }

        public Criteria andInatmoneyIsNotNull() {
            addCriterion("INATMONEY is not null");
            return (Criteria) this;
        }

        public Criteria andInatmoneyEqualTo(Short value) {
            addCriterion("INATMONEY =", value, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyNotEqualTo(Short value) {
            addCriterion("INATMONEY <>", value, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyGreaterThan(Short value) {
            addCriterion("INATMONEY >", value, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyGreaterThanOrEqualTo(Short value) {
            addCriterion("INATMONEY >=", value, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyLessThan(Short value) {
            addCriterion("INATMONEY <", value, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyLessThanOrEqualTo(Short value) {
            addCriterion("INATMONEY <=", value, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyIn(List<Short> values) {
            addCriterion("INATMONEY in", values, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyNotIn(List<Short> values) {
            addCriterion("INATMONEY not in", values, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyBetween(Short value1, Short value2) {
            addCriterion("INATMONEY between", value1, value2, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andInatmoneyNotBetween(Short value1, Short value2) {
            addCriterion("INATMONEY not between", value1, value2, "inatmoney");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceIsNull() {
            addCriterion("IAOUTPRICE is null");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceIsNotNull() {
            addCriterion("IAOUTPRICE is not null");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceEqualTo(Short value) {
            addCriterion("IAOUTPRICE =", value, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceNotEqualTo(Short value) {
            addCriterion("IAOUTPRICE <>", value, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceGreaterThan(Short value) {
            addCriterion("IAOUTPRICE >", value, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceGreaterThanOrEqualTo(Short value) {
            addCriterion("IAOUTPRICE >=", value, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceLessThan(Short value) {
            addCriterion("IAOUTPRICE <", value, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceLessThanOrEqualTo(Short value) {
            addCriterion("IAOUTPRICE <=", value, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceIn(List<Short> values) {
            addCriterion("IAOUTPRICE in", values, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceNotIn(List<Short> values) {
            addCriterion("IAOUTPRICE not in", values, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceBetween(Short value1, Short value2) {
            addCriterion("IAOUTPRICE between", value1, value2, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andIaoutpriceNotBetween(Short value1, Short value2) {
            addCriterion("IAOUTPRICE not between", value1, value2, "iaoutprice");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeIsNull() {
            addCriterion("CPZNUM_INCOME is null");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeIsNotNull() {
            addCriterion("CPZNUM_INCOME is not null");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeEqualTo(String value) {
            addCriterion("CPZNUM_INCOME =", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeNotEqualTo(String value) {
            addCriterion("CPZNUM_INCOME <>", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeGreaterThan(String value) {
            addCriterion("CPZNUM_INCOME >", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeGreaterThanOrEqualTo(String value) {
            addCriterion("CPZNUM_INCOME >=", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeLessThan(String value) {
            addCriterion("CPZNUM_INCOME <", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeLessThanOrEqualTo(String value) {
            addCriterion("CPZNUM_INCOME <=", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeLike(String value) {
            addCriterion("CPZNUM_INCOME like", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeNotLike(String value) {
            addCriterion("CPZNUM_INCOME not like", value, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeIn(List<String> values) {
            addCriterion("CPZNUM_INCOME in", values, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeNotIn(List<String> values) {
            addCriterion("CPZNUM_INCOME not in", values, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeBetween(String value1, String value2) {
            addCriterion("CPZNUM_INCOME between", value1, value2, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumIncomeNotBetween(String value1, String value2) {
            addCriterion("CPZNUM_INCOME not between", value1, value2, "cpznumIncome");
            return (Criteria) this;
        }

        public Criteria andCpznumCostIsNull() {
            addCriterion("CPZNUM_COST is null");
            return (Criteria) this;
        }

        public Criteria andCpznumCostIsNotNull() {
            addCriterion("CPZNUM_COST is not null");
            return (Criteria) this;
        }

        public Criteria andCpznumCostEqualTo(String value) {
            addCriterion("CPZNUM_COST =", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostNotEqualTo(String value) {
            addCriterion("CPZNUM_COST <>", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostGreaterThan(String value) {
            addCriterion("CPZNUM_COST >", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostGreaterThanOrEqualTo(String value) {
            addCriterion("CPZNUM_COST >=", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostLessThan(String value) {
            addCriterion("CPZNUM_COST <", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostLessThanOrEqualTo(String value) {
            addCriterion("CPZNUM_COST <=", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostLike(String value) {
            addCriterion("CPZNUM_COST like", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostNotLike(String value) {
            addCriterion("CPZNUM_COST not like", value, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostIn(List<String> values) {
            addCriterion("CPZNUM_COST in", values, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostNotIn(List<String> values) {
            addCriterion("CPZNUM_COST not in", values, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostBetween(String value1, String value2) {
            addCriterion("CPZNUM_COST between", value1, value2, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andCpznumCostNotBetween(String value1, String value2) {
            addCriterion("CPZNUM_COST not between", value1, value2, "cpznumCost");
            return (Criteria) this;
        }

        public Criteria andInvnameIsNull() {
            addCriterion("INVNAME is null");
            return (Criteria) this;
        }

        public Criteria andInvnameIsNotNull() {
            addCriterion("INVNAME is not null");
            return (Criteria) this;
        }

        public Criteria andInvnameEqualTo(String value) {
            addCriterion("INVNAME =", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameNotEqualTo(String value) {
            addCriterion("INVNAME <>", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameGreaterThan(String value) {
            addCriterion("INVNAME >", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameGreaterThanOrEqualTo(String value) {
            addCriterion("INVNAME >=", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameLessThan(String value) {
            addCriterion("INVNAME <", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameLessThanOrEqualTo(String value) {
            addCriterion("INVNAME <=", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameLike(String value) {
            addCriterion("INVNAME like", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameNotLike(String value) {
            addCriterion("INVNAME not like", value, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameIn(List<String> values) {
            addCriterion("INVNAME in", values, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameNotIn(List<String> values) {
            addCriterion("INVNAME not in", values, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameBetween(String value1, String value2) {
            addCriterion("INVNAME between", value1, value2, "invname");
            return (Criteria) this;
        }

        public Criteria andInvnameNotBetween(String value1, String value2) {
            addCriterion("INVNAME not between", value1, value2, "invname");
            return (Criteria) this;
        }

        public Criteria andCdepcodeIsNull() {
            addCriterion("CDEPCODE is null");
            return (Criteria) this;
        }

        public Criteria andCdepcodeIsNotNull() {
            addCriterion("CDEPCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCdepcodeEqualTo(String value) {
            addCriterion("CDEPCODE =", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeNotEqualTo(String value) {
            addCriterion("CDEPCODE <>", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeGreaterThan(String value) {
            addCriterion("CDEPCODE >", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeGreaterThanOrEqualTo(String value) {
            addCriterion("CDEPCODE >=", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeLessThan(String value) {
            addCriterion("CDEPCODE <", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeLessThanOrEqualTo(String value) {
            addCriterion("CDEPCODE <=", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeLike(String value) {
            addCriterion("CDEPCODE like", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeNotLike(String value) {
            addCriterion("CDEPCODE not like", value, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeIn(List<String> values) {
            addCriterion("CDEPCODE in", values, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeNotIn(List<String> values) {
            addCriterion("CDEPCODE not in", values, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeBetween(String value1, String value2) {
            addCriterion("CDEPCODE between", value1, value2, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCdepcodeNotBetween(String value1, String value2) {
            addCriterion("CDEPCODE not between", value1, value2, "cdepcode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeIsNull() {
            addCriterion("CPERSONCODE is null");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeIsNotNull() {
            addCriterion("CPERSONCODE is not null");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeEqualTo(String value) {
            addCriterion("CPERSONCODE =", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeNotEqualTo(String value) {
            addCriterion("CPERSONCODE <>", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeGreaterThan(String value) {
            addCriterion("CPERSONCODE >", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeGreaterThanOrEqualTo(String value) {
            addCriterion("CPERSONCODE >=", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeLessThan(String value) {
            addCriterion("CPERSONCODE <", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeLessThanOrEqualTo(String value) {
            addCriterion("CPERSONCODE <=", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeLike(String value) {
            addCriterion("CPERSONCODE like", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeNotLike(String value) {
            addCriterion("CPERSONCODE not like", value, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeIn(List<String> values) {
            addCriterion("CPERSONCODE in", values, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeNotIn(List<String> values) {
            addCriterion("CPERSONCODE not in", values, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeBetween(String value1, String value2) {
            addCriterion("CPERSONCODE between", value1, value2, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andCpersoncodeNotBetween(String value1, String value2) {
            addCriterion("CPERSONCODE not between", value1, value2, "cpersoncode");
            return (Criteria) this;
        }

        public Criteria andRefTypeIsNull() {
            addCriterion("REF_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andRefTypeIsNotNull() {
            addCriterion("REF_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andRefTypeEqualTo(String value) {
            addCriterion("REF_TYPE =", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeNotEqualTo(String value) {
            addCriterion("REF_TYPE <>", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeGreaterThan(String value) {
            addCriterion("REF_TYPE >", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeGreaterThanOrEqualTo(String value) {
            addCriterion("REF_TYPE >=", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeLessThan(String value) {
            addCriterion("REF_TYPE <", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeLessThanOrEqualTo(String value) {
            addCriterion("REF_TYPE <=", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeLike(String value) {
            addCriterion("REF_TYPE like", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeNotLike(String value) {
            addCriterion("REF_TYPE not like", value, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeIn(List<String> values) {
            addCriterion("REF_TYPE in", values, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeNotIn(List<String> values) {
            addCriterion("REF_TYPE not in", values, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeBetween(String value1, String value2) {
            addCriterion("REF_TYPE between", value1, value2, "refType");
            return (Criteria) this;
        }

        public Criteria andRefTypeNotBetween(String value1, String value2) {
            addCriterion("REF_TYPE not between", value1, value2, "refType");
            return (Criteria) this;
        }

        public Criteria andRefIdIsNull() {
            addCriterion("REF_ID is null");
            return (Criteria) this;
        }

        public Criteria andRefIdIsNotNull() {
            addCriterion("REF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andRefIdEqualTo(Short value) {
            addCriterion("REF_ID =", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotEqualTo(Short value) {
            addCriterion("REF_ID <>", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThan(Short value) {
            addCriterion("REF_ID >", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdGreaterThanOrEqualTo(Short value) {
            addCriterion("REF_ID >=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThan(Short value) {
            addCriterion("REF_ID <", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdLessThanOrEqualTo(Short value) {
            addCriterion("REF_ID <=", value, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdIn(List<Short> values) {
            addCriterion("REF_ID in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotIn(List<Short> values) {
            addCriterion("REF_ID not in", values, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdBetween(Short value1, Short value2) {
            addCriterion("REF_ID between", value1, value2, "refId");
            return (Criteria) this;
        }

        public Criteria andRefIdNotBetween(Short value1, Short value2) {
            addCriterion("REF_ID not between", value1, value2, "refId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated do_not_delete_during_merge Fri Nov 09 15:49:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CW.CW_GL_INCOME_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}