package appo.task.domain;

import java.util.Date;

public class CwGlIncomeCost {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.ID
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private Date lastUpdatedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.COMPANYCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String companycode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.BILL_SOURCE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String billSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CBDLCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String cbdlcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.SHIP_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private Date shipDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.INCOME_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private Date incomeDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CCUSCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String ccuscode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CINVCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String cinvcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.IQUANTITY
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float iquantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.EXCHANGE_NAME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String exchangeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.EXCHANGE_RATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float exchangeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.ITAXUNITPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float itaxunitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.IUNITPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float iunitprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.INATMONEY
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float inatmoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.IAOUTPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float iaoutprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CPZNUM_INCOME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String cpznumIncome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CPZNUM_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String cpznumCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.INVNAME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String invname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CDEPCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String cdepcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.CPERSONCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String cpersoncode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.REF_TYPE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private String refType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column CW.CW_GL_INCOME_COST.REF_ID
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    private float refId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.ID
     *
     * @return the value of CW.CW_GL_INCOME_COST.ID
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.ID
     *
     * @param id the value for CW.CW_GL_INCOME_COST.ID
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setId(float id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.LAST_UPDATED_DATE
     *
     * @return the value of CW.CW_GL_INCOME_COST.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.LAST_UPDATED_DATE
     *
     * @param lastUpdatedDate the value for CW.CW_GL_INCOME_COST.LAST_UPDATED_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setLastUpdatedDate(Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.COMPANYCODE
     *
     * @return the value of CW.CW_GL_INCOME_COST.COMPANYCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCompanycode() {
        return companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.COMPANYCODE
     *
     * @param companycode the value for CW.CW_GL_INCOME_COST.COMPANYCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCompanycode(String companycode) {
        this.companycode = companycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.BILL_SOURCE
     *
     * @return the value of CW.CW_GL_INCOME_COST.BILL_SOURCE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getBillSource() {
        return billSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.BILL_SOURCE
     *
     * @param billSource the value for CW.CW_GL_INCOME_COST.BILL_SOURCE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setBillSource(String billSource) {
        this.billSource = billSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CBDLCODE
     *
     * @return the value of CW.CW_GL_INCOME_COST.CBDLCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCbdlcode() {
        return cbdlcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CBDLCODE
     *
     * @param cbdlcode the value for CW.CW_GL_INCOME_COST.CBDLCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCbdlcode(String cbdlcode) {
        this.cbdlcode = cbdlcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.SHIP_DATE
     *
     * @return the value of CW.CW_GL_INCOME_COST.SHIP_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public Date getShipDate() {
        return shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.SHIP_DATE
     *
     * @param shipDate the value for CW.CW_GL_INCOME_COST.SHIP_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setShipDate(Date shipDate) {
        this.shipDate = shipDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.INCOME_DATE
     *
     * @return the value of CW.CW_GL_INCOME_COST.INCOME_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public Date getIncomeDate() {
        return incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.INCOME_DATE
     *
     * @param incomeDate the value for CW.CW_GL_INCOME_COST.INCOME_DATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setIncomeDate(Date incomeDate) {
        this.incomeDate = incomeDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CCUSCODE
     *
     * @return the value of CW.CW_GL_INCOME_COST.CCUSCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCcuscode() {
        return ccuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CCUSCODE
     *
     * @param ccuscode the value for CW.CW_GL_INCOME_COST.CCUSCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCcuscode(String ccuscode) {
        this.ccuscode = ccuscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CINVCODE
     *
     * @return the value of CW.CW_GL_INCOME_COST.CINVCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCinvcode() {
        return cinvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CINVCODE
     *
     * @param cinvcode the value for CW.CW_GL_INCOME_COST.CINVCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCinvcode(String cinvcode) {
        this.cinvcode = cinvcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.IQUANTITY
     *
     * @return the value of CW.CW_GL_INCOME_COST.IQUANTITY
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getIquantity() {
        return iquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.IQUANTITY
     *
     * @param iquantity the value for CW.CW_GL_INCOME_COST.IQUANTITY
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setIquantity(float iquantity) {
        this.iquantity = iquantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.EXCHANGE_NAME
     *
     * @return the value of CW.CW_GL_INCOME_COST.EXCHANGE_NAME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getExchangeName() {
        return exchangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.EXCHANGE_NAME
     *
     * @param exchangeName the value for CW.CW_GL_INCOME_COST.EXCHANGE_NAME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setExchangeName(String exchangeName) {
        this.exchangeName = exchangeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.EXCHANGE_RATE
     *
     * @return the value of CW.CW_GL_INCOME_COST.EXCHANGE_RATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getExchangeRate() {
        return exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.EXCHANGE_RATE
     *
     * @param exchangeRate the value for CW.CW_GL_INCOME_COST.EXCHANGE_RATE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setExchangeRate(float exchangeRate) {
        this.exchangeRate = exchangeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.ITAXUNITPRICE
     *
     * @return the value of CW.CW_GL_INCOME_COST.ITAXUNITPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getItaxunitprice() {
        return itaxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.ITAXUNITPRICE
     *
     * @param itaxunitprice the value for CW.CW_GL_INCOME_COST.ITAXUNITPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setItaxunitprice(float itaxunitprice) {
        this.itaxunitprice = itaxunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.IUNITPRICE
     *
     * @return the value of CW.CW_GL_INCOME_COST.IUNITPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getIunitprice() {
        return iunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.IUNITPRICE
     *
     * @param iunitprice the value for CW.CW_GL_INCOME_COST.IUNITPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setIunitprice(float iunitprice) {
        this.iunitprice = iunitprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.INATMONEY
     *
     * @return the value of CW.CW_GL_INCOME_COST.INATMONEY
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getInatmoney() {
        return inatmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.INATMONEY
     *
     * @param inatmoney the value for CW.CW_GL_INCOME_COST.INATMONEY
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setInatmoney(float inatmoney) {
        this.inatmoney = inatmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.IAOUTPRICE
     *
     * @return the value of CW.CW_GL_INCOME_COST.IAOUTPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getIaoutprice() {
        return iaoutprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.IAOUTPRICE
     *
     * @param iaoutprice the value for CW.CW_GL_INCOME_COST.IAOUTPRICE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setIaoutprice(float iaoutprice) {
        this.iaoutprice = iaoutprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CPZNUM_INCOME
     *
     * @return the value of CW.CW_GL_INCOME_COST.CPZNUM_INCOME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCpznumIncome() {
        return cpznumIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CPZNUM_INCOME
     *
     * @param cpznumIncome the value for CW.CW_GL_INCOME_COST.CPZNUM_INCOME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCpznumIncome(String cpznumIncome) {
        this.cpznumIncome = cpznumIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CPZNUM_COST
     *
     * @return the value of CW.CW_GL_INCOME_COST.CPZNUM_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCpznumCost() {
        return cpznumCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CPZNUM_COST
     *
     * @param cpznumCost the value for CW.CW_GL_INCOME_COST.CPZNUM_COST
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCpznumCost(String cpznumCost) {
        this.cpznumCost = cpznumCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.INVNAME
     *
     * @return the value of CW.CW_GL_INCOME_COST.INVNAME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getInvname() {
        return invname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.INVNAME
     *
     * @param invname the value for CW.CW_GL_INCOME_COST.INVNAME
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setInvname(String invname) {
        this.invname = invname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CDEPCODE
     *
     * @return the value of CW.CW_GL_INCOME_COST.CDEPCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCdepcode() {
        return cdepcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CDEPCODE
     *
     * @param cdepcode the value for CW.CW_GL_INCOME_COST.CDEPCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCdepcode(String cdepcode) {
        this.cdepcode = cdepcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.CPERSONCODE
     *
     * @return the value of CW.CW_GL_INCOME_COST.CPERSONCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getCpersoncode() {
        return cpersoncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.CPERSONCODE
     *
     * @param cpersoncode the value for CW.CW_GL_INCOME_COST.CPERSONCODE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setCpersoncode(String cpersoncode) {
        this.cpersoncode = cpersoncode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.REF_TYPE
     *
     * @return the value of CW.CW_GL_INCOME_COST.REF_TYPE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public String getRefType() {
        return refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.REF_TYPE
     *
     * @param refType the value for CW.CW_GL_INCOME_COST.REF_TYPE
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setRefType(String refType) {
        this.refType = refType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column CW.CW_GL_INCOME_COST.REF_ID
     *
     * @return the value of CW.CW_GL_INCOME_COST.REF_ID
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public float getRefId() {
        return refId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column CW.CW_GL_INCOME_COST.REF_ID
     *
     * @param refId the value for CW.CW_GL_INCOME_COST.REF_ID
     *
     * @mbg.generated Fri Nov 09 15:49:07 CST 2018
     */
    public void setRefId(float refId) {
        this.refId = refId;
    }
}